name = "medium-frontend"
compatibility_date = "2025-01-01"

# Required by Cloudflare Pages when using wrangler.toml
pages_build_output_dir = "dist"

[functions]
directory = "functions"

[vars]
BACKEND_URL = "https://conceptual-wileen-medium-test-5b91bdf0.koyeb.app"

